### ISSUE TITLE
CTC code

### ISSUE THREAD

**Issue by matthijsvk** [Santara/e2e_ASR_Lasagne_CTC#1]
Hello Santara,

I was reading your code; it seems really interesting and could be quite useful to me.
The file for CTC classification seems to be missing; would it be possible to add it to the repository?
Thanks,

Matthijs

**Comment by Santara** [comment]
Hi,
The Project has been moved here: https://github.com/KGPML/KGP-ASR 
This contains the functions you are looking for.
Thanks
Anirban
